#!/bin/sh

if [ remove = "$1" ] || [ abort-install = "$1" ] || [ disappear = "$1" ]
then
  dpkg-divert --package teacats-zonefiles --rename --remove --divert /etc/bind/upstream-named.conf /etc/bind/named.conf
fi
